<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net481;net8.0</TargetFrameworks>
		<Title>XenCenterOVF</Title>
		<Description>XCP-ng Center library</Description>
		<RootNamespace>XenOvf</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\XenCenterLib\XenCenterLib.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net481'">
		<Reference Include="System.Management" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="System.Management" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Content.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Content.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Messages.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Messages.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Content.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Content.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Messages.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Messages.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>